### ISSUE TITLE
Fix ugly card color

### ISSUE THREAD

**Issue by g-liu** [aaronnech/CheckYourBias#1]
![image](https://cloud.githubusercontent.com/assets/3281451/12775411/a5a9b13c-ca02-11e5-9c87-f0e424466cee.png)

I expect the default card color to be white, but it is this ugly color of gray.

**Comment by aaronnech** [comment]
For this check out src/client/theme/Theme.ts

**Comment by g-liu** [comment]
Looks like the card color is fixed, but slider color is still wonky. The easiest fix for this is just to go to the default theme and not define a palette.

Closing for now as the main issue has been resolved.
