### ISSUE TITLE
Submitting content without internet hangs

### ISSUE THREAD

**Issue by rdrapeau** [aaronnech/CheckYourBias#13]
When a user attempts to submit content without a valid internet connection, the app will hang until a connection is established. It would be better to either store this locally, or let the user know that an internet connection is required to submit content.

**Comment by g-liu** [comment]
It may be a stretch feature to enable offline functionality for all parts of our application, not just the submitting content part of it. For example, handling voting of issues when the user is offline, or trying to get next issue when the user is offline.

**Comment by rdrapeau** [comment]
For now I will display a popup error saying an internet connection is required to submit content (preventing the app from hanging).
