### ISSUE TITLE
Calling User.getNextIssue throws "nextIssue.category.indexOf is not a function"

### ISSUE THREAD

**Issue by g-liu** [aaronnech/CheckYourBias#20]
To reproduce this issue:
- Log in to the application
- On the database backend, delete all of your rated issues.
- Refresh the application, re-log in if necessary
- Vote on an issue and click "Next Issue". Repeat as necessary.
- Eventually you will notice the following error in the JavaScript console:

`Uncaught TypeError: nextIssue.category.indexOf is not a function`

This bug can be replicated if the user has already voted on all available issues, and attempts to get a new issue.

The error points to a line in the `User.getNextIssue` function.

**Comment by huynick** [comment]
There was an issue in the prod data where category was a string rather than an array. Fixed!
