### ISSUE TITLE
Fix style on RateViewpointsComponent

### ISSUE THREAD

**Issue by g-liu** [aaronnech/CheckYourBias#4]
Currently, the slider looks like this:
![image](https://cloud.githubusercontent.com/assets/3281451/12864268/0eb0ef4a-cc3a-11e5-85bc-18da1cee8e98.png)
We want the slider to look like this:
![image](https://cloud.githubusercontent.com/assets/3281451/12864270/265b9c6c-cc3a-11e5-8600-c668a2315303.png)

The confirm button must also be made a floating toucher button, or any other button style as deemed appropriate by Google Material Design guidelines.

**Comment by g-liu** [comment]
The slider is currently implemented as a single React Component:

```
<Slider min={0} max={5} defaultValue={2.5} onChange={this.changeAgreement} />
```

The challenge here is to apply styles _within_ the slider. As far as I know this is not something you can achieve with the `style` attribute. See the screenshot below:

![image](https://cloud.githubusercontent.com/assets/3281451/12864342/8051f430-cc3c-11e5-8571-0d1019db7630.png)

I want to change that element's `background-color` to something else. @aaronnech - any advice on this? My first thought is to somehow extend the component and modify what I need, but you're the expert here.

**Comment by aaronnech** [comment]
Feel free just to use a custom slider if the material design one is giving you too much pain. I saw some GH issues with the material design react slider right now.

**Comment by aaronnech** [comment]
Just CSS a normal slider till it looks good I'd say.
