### ISSUE TITLE
Retrieve issues for all categories, not just one.

### ISSUE THREAD

**Issue by g-liu** [aaronnech/CheckYourBias#41]
Currently, `RateViewpointsComponent` is hard-coded to just retrieve issues from category "0". We need to distribute the fetching issues from different categories in a "smart" manner, so that the user sees a variety of issues.

**Comment by g-liu** [comment]
This might be better handled in the backend.

@huynick @rhwilk @toddis I am thinking to make the category parameter optional in `User.getNextIssue`. This will support the use case where I just want to get any issue that is available to me. When the caller does not supply the category parameter, `getNextIssue` should choose randomly from all available issues. Or, it could even use a weighted random algorithm for choosing the next issue. For example, if this was the distribution of unvoted issues in the database:

<table>
<tr>
<th>Category Id</th>
<th>Number of un-voted issues</th>
<th>% chance of selecting issue from that category</th>
</tr>
<tr>
<td>2</td>
<td>6</td>
<td>75%</td>
</tr>
<tr>
<td>5</td>
<td>2</td>
<td>25%</td>
</tr>
</table>

Please reply and let me know what you think about changing the issue selection algorithm!

**Comment by rhwilk** [comment]
I can update getNextIssue so that if it's given some nonstandard value (say, "all") as the category id, it won't check the category of the issue. As the issue is picked randomly before any category checks are made, I think this effectively creates the weighting you mention automatically, unless I'm misunderstanding.

**Comment by g-liu** [comment]
I was thinking, if I call

<pre>User.getNextIssue(userId, null, function() { ... })</pre>

that null param can say "give me an issue from any category".

Then you can check in the implementation:

<pre>if (category === null)</pre>

instead of parsing the string and checking for a nonstandard value.
