### ISSUE TITLE
UI - Need alternative to red underline for indicating required field

### ISSUE THREAD

**Issue by g-liu** [aaronnech/CheckYourBias#43]
In the `CrowdsourcingSubmitContentComponent`, we are currently using red underlines to denote required fields. We need to think of a better way to indicate that the fields are required.

My thought here is that we can use red asterisks (this is a convention) to indicate that the field is required. When and only when the user attempts to submit the form without all required fields filled out, we show the red lines on the required fields that the user did not fill out. Of course, this is open to discussion.

**Comment by rdrapeau** [comment]
Yeah I also thought red asterisks would be a good idea. I think this is a good idea
