### ISSUE TITLE
Owner of content should not be able to approve own submitted content

### ISSUE THREAD

**Issue by g-liu** [aaronnech/CheckYourBias#44]
Currently, the crowdsourcing approval implementation allows any admin -- including the original submitter -- to approve or reject submitted content. This needs to change such that only admins, _minus the submitter_, can change the approval status of submitted content.

**Comment by rdrapeau** [comment]
I don't think this is necessary: If someone submitted content and can see it in the approval tool -> that means they are an admin, which implies they are a trusted source... It's not like a normal user of the app would have these privileges.

**Comment by g-liu** [comment]
Quoting @SonjaKhan (and Nacho):

> owner of content shouldn’t be able to approve their content

I would assume this also extends to admins.

**Comment by sonjakhan** [comment]
I think it makes sense to prevent a user from approving their own content, even if they are an admin.

**Comment by rdrapeau** [comment]
I know, I'm saying that isn't necessary. If you're an admin, aren't you a verified and trusted source in this case?

**Comment by sonjakhan** [comment]
So this is actually a backend issue. Issue.getUnapprovedIssue should filter out unapproved issues that a user has authored. @toddis @rhwilk @huynick can one of you take this on? I looked at the backend code but I don't understand how Firebase works
