### ISSUE TITLE
Provide user with reason for each candidate in "Your Candidates"

### ISSUE THREAD

**Issue by g-liu** [aaronnech/CheckYourBias#45]
The Your Candidates page currently provides the user with no information about why the candidates are there, and why they are ranked as such. We should supply the user with information about the candidates and how much the user agrees with such candidates. Such information could include topics of issues agreed on, number of issues agreed on, etc.

Backend team has already provided us a ranking for each candidate as a single number, but the number is arbitrarily chosen and only used for comparison.

**Comment by g-liu** [comment]
![image](https://cloud.githubusercontent.com/assets/3281451/13443893/1021cf0c-dfb8-11e5-97ad-17dda7e03052.png)

As it stands right now, we could push this into `master`. Adding candidate avatars (#34, #52) <del>can be done in a separate feature or branch</del><ins>is also done</ins>. @SonjaKhan let me know what you think!

**Comment by ravnon** [comment]
The wording "50% similar views as you" is a little awkward/clunky. What about something like "50% similarity" or "x% in common" just "x% similar views". 

Otherwise, looks really good! Well done.

**Comment by sonjakhan** [comment]
@g-liu nice work! You should merge this into master
