### ISSUE TITLE
Some issue authors on the Political Profile page are `undefined`

### ISSUE THREAD

**Issue by g-liu** [aaronnech/CheckYourBias#47]
See screenshot. I did a quick inspection and the root cause must be the `Issue.getIssueAuthor` method, which can return undefined if `this.getIssueAuthorID(issue)` is out of bounds. We need to handle this case for any arbitrary issue.
![image](https://cloud.githubusercontent.com/assets/3281451/13339058/ad548148-dbda-11e5-9aba-2e9ae0963847.png)

**Comment by sonjakhan** [comment]
@ravnon This came up during user testing as well

**Comment by ravnon** [comment]
This is caused by the line"if (issue.candidateRatings[key] == "4”)” in Issue.ts. I am currently working with the backend team to resolve this.

**Comment by rhwilk** [comment]
I think the actual issue causing the undefineds was that some of the early issues were incorrectly labeled as direct quotes when they were really general content - so I fixed those in the database - but the way authors of direct quotes was being determined was pretty janky, so I added an author field to issues (holds the candidate id of the author of a direct quote). This required a bit of poking around in the submit content component to hook that up properly, so someone from that side of things might want to make sure the changes there are acceptable.

**Comment by ravnon** [comment]
I looks like @rhwilk solved the problem with that fix. Well done!
