### ISSUE TITLE
Add option to edit and remove information when submitting content

### ISSUE THREAD

**Issue by g-liu** [aaronnech/CheckYourBias#48]
Currently, the Submit Content screen does not allow you to remove any selected categories, or sources. To reproduce this bug:
1. Log in to the app
2. Go to "Submit Content"
3. Enter a valid URL in Source, click Add source.
   Notice how it is not possible to remove the source
4. Select a category from the dropdown
   Notice how it is not possible to remove that category

Users should be given the freedom to add and remove sources and categories. This is especially important if they make a mistake. Additionally, allowing the user to edit the source would be a huge UX improvement.

**Comment by rdrapeau** [comment]
This also extends to candidate selection in general content
