### ISSUE TITLE
Noop setstate on main component

### ISSUE THREAD

**Issue by aaronnech** [aaronnech/CheckYourBias#49]
![image](https://cloud.githubusercontent.com/assets/3673255/13343403/1f94d0d4-dc01-11e5-9c14-4942c2cd8a58.png)

**Comment by aaronnech** [comment]
Old profile bug

**Comment by g-liu** [comment]
Is it necessary that all of us who have this bug need to nuke our user profiles? I am still getting this error even on the latest commit.

**Comment by g-liu** [comment]
Confirmed that I am indeed to reproduce this bug. This is probably related to the `onSignIn` function in `FacebookAuthPageComponent`. However, it does not seem to affect any functionality in the application.
