### ISSUE TITLE
category undefined? Your Candidates Page

### ISSUE THREAD

**Issue by aaronnech** [aaronnech/CheckYourBias#50]
![image](https://cloud.githubusercontent.com/assets/3673255/13343418/5bf1d7a2-dc01-11e5-8a76-fbfb758a228e.png)

**Comment by g-liu** [comment]
I am unable to reproduce this issue. `main.js:2673` is code within `User.getRankings`.

Could you supply a list of steps on reproducing this error, and check that you have the latest pull?

**Comment by aaronnech** [comment]
Might be due to an old user profile. I'll remove my profile and try again

**Comment by aaronnech** [comment]
Yup, old profile. Must be trying to generate a ranking off old data or something.
