### ISSUE TITLE
Having any skipped issues in the database will cause non-deterministic behavior with getting the next issue

### ISSUE THREAD

**Issue by g-liu** [aaronnech/CheckYourBias#51]
This issue is in reference to #42 which is currently in progress at the time of this issue filing. I expect that if I call `User.skipIssue(...)`, and subsequently call `User.getNextIssue()`, the latter will return me an issue so long as there are approved issues for the category that I specify. However this is not the case.
# To reproduce this bug:
1. Check out the buggy branch
   <pre>
   # I made a branch where I've included code that implements skipping, but suffers from this bug
   git checkout geoff_skip_issue_buggy
   git pull
   npm run-script serve
   </pre>
2. Point your browser to `localhost:1337`, log in if necessary.
3. Ensure that you have no rated issues, or skipped issues in the database. Clear these rated/skipped issues and refresh your browser.
4. Skip the first issue that you see
5. Refresh the page a few times, with the JavaScript console open. You'll see that occasionally, `getNextIssue` returns `null`, and other times, it will return an actual issue.

You may repeat steps 4 and 5 for 2, 3, or more issues, and see the same behavior.

When fixing this bug, you can add commits directly to the `geoff_skip_issue` branch.

**Comment by rhwilk** [comment]
Currently attemptedIssues tracks issues by index, while the elements added to it from skippedIssues are tracked by ID. One or the other will need to be altered for getNextIssue to function properly.

**Comment by g-liu** [comment]
It sounds more canonical if `attemptedIssues` tracked issues by issue ID. This is because the front-end knows which unique issue it is currently displaying to the user by the issue ID. It does not necessarily have access to the index of the issue in the db, which can change as issues are added and deleted.

**Comment by rhwilk** [comment]
I agree - it also makes pre-filtering more convenient.

**Comment by g-liu** [comment]
Unfortunately, the same behavior is still occurring and can be reproduced with the steps shown in the original post. I wonder if it's a problem with the [front-end logic for skipping an issue](https://github.com/aaronnech/CheckYourBias/blob/c909cec7a85c890fb77d5b044e2b617821a9ed5e/src/client/component/RateViewpointsComponent.jsx#L153-L172)...

Additionally, I ran the tests and `testGetNextIssueSkip` in `User.test.ts` is failing its assertion. It might be helpful to have another set of eyes on this issue.
