### ISSUE TITLE
Return candidate ids for each candidate in User.getRankings

### ISSUE THREAD

**Issue by g-liu** [aaronnech/CheckYourBias#52]
The current return type of `User.getRankings` is an array of Candidate objects. However, the Candidate objects themselves are missing the `candidateId` field. This will be required in the front-end in order to retrieve the corresponding avatar image of the candidate. We cannot rely on the index of the Candidate object as its id, since the array returned is sorted by ranking and not by candidate ID.

This issue is closed once an additional field representing the candidate id is added for every candidate returned in `User.getRankings`.

**Comment by huynick** [comment]
I did it!!
