### ISSUE TITLE
URL validation on Submit Content catches false negatives

### ISSUE THREAD

**Issue by g-liu** [aaronnech/CheckYourBias#56]
Currently, URL validation on the Submit Content page may not let legitimate URLs through.

For example, this URL will fail:

http://dailycaller.com/2016/02/27/heres-where-the-2016-candidates-stand-on-global-warming/

even though it links to a legitimate page.

We should change and test the method of validation to make sure that it accepts legitimate URLs. It might be wise to [look into the `type` attribute](http://www.material-ui.com/#/components/text-field) of the `TextField` component.

**Comment by rdrapeau** [comment]
This URL you gave seems to be accepted just fine?

<img width="689" alt="screen shot 2016-03-01 at 10 59 29 am" src="https://cloud.githubusercontent.com/assets/3769522/13438172/b43400c2-df9c-11e5-9614-5bdc1657baca.png">

**Comment by g-liu** [comment]
@rdrapeau Okay you are right, it works. I forgot to press the Add Source button. So now this becomes a UI issue. I assumed that if I only had a single source to submit, all I had to do was paste the URL into that field (without hitting Add Source). This is not the case however, as I have to press the Add Source button even if I'm only submitting content with one source URL.

I will close this issue for now, but the UI is something worth looking into.
