### ISSUE TITLE
Remove all references to Constants.CANDIDATES and Constants.CATEGORIES

### ISSUE THREAD

**Issue by g-liu** [aaronnech/CheckYourBias#59]
These two Constants fields should have been deprecated long ago, but a (recent search)[https://github.com/aaronnech/CheckYourBias/search?utf8=%E2%9C%93&q=%22Constants.CANDIDATES%22] on the latest commits reveals at least one chunk of code is still referencing that.

This issue is closed once that `Constants.CANDIDATES` and `Constants.CATEGORIES` fields are removed from `Constants.ts`, and all code referencing these two objects are restructured such that they pull candidates and/or categories from the database.

**Comment by ravnon** [comment]
Thanks for the heads up. Transitioned to cached values in: https://github.com/aaronnech/CheckYourBias/commit/c555494685bdeb0a042124377518d223613fc715
