### ISSUE TITLE
Submit Content Does Not Work

### ISSUE THREAD

**Issue by ravnon** [aaronnech/CheckYourBias#65]
Repro Steps:
1. Fill in fields on Content Submission Page
2. Press Submit Issue
3. It does not work.

EXPECTED:
3. It does work.

<img width="455" alt="screen shot 2016-03-07 at 9 07 17 pm" src="https://cloud.githubusercontent.com/assets/5475796/13593071/01028de6-e4ad-11e5-8660-d9281ff45e1d.png">

**Comment by g-liu** [comment]
I could not reproduce this issue. Tried submitting under General Content, Direct Quote, with different combinations of candidates, sources, and categories. However, I was unsuccessful in reproducing that error you had.

Could you post exactly what you were trying to submit?
